describe("FactoryGame", function()
	it("test framework is operational", function()
		assert.is_true(true)
	end)

	describe("plugin_harness", function()
		local harness = require("tests.helpers.plugin_harness")

		it("creates an isolated context", function()
			local ctx = harness.create_context()
			assert.is_table(ctx)
			assert.is_table(ctx.world)
			assert.is_table(ctx.bus)
			assert.is_table(ctx.config)
			assert.is_table(ctx.services)
		end)

		it("tears down cleanly", function()
			local ctx = harness.create_context()
			ctx.world:addEntity({ id = 1 })
			ctx.bus:on("test", function() end)
			harness.teardown(ctx)
			assert.are.equal(0, #ctx.world._entities)
		end)
	end)
end)
